#!/usr/bin/python
"""
Script for non-interactive, faster-than-realtime multicopter simulation over a predefined time window.
Currently, results are plotted but not saved.

"""
from __future__ import division
import numpy as np; npl = np.linalg

from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D

from multicopter import motion
from multicopter.bois import quadboi

# Time window
dt = 0.03
duration = 9
T = np.arange(0, duration, dt)

# Wacky controller to make things interesting
def controller(state):
    if state.pose.lin[2] < 2:
        ui = 0.8 * quadboi.thruster_list[0].max_effort
        rando = (1.005 - 0.995)*np.random.sample() + 0.995
    else:
        ui = 0
        rando = 1
    # ui = np.sqrt((quadboi.mass*9.81/4)/1e-7)  # open-loop hover
    return {"front": ui, "back": ui, "left": rando*ui, "right": ui}

# Scheduled external disturbance wrench
wind = lambda t: motion.Wrench([0, 0, 0], [0, 0, 0])  # same as None

# Initial condition
P = [[0, 0, 10]]
Q = [[0, 0, 0, 1]]
V = [[0, 0, 0]]
W = [[0, 0, 0]]
states = [motion.State(motion.Pose(P[0], Q[0]), motion.Twist(V[0], W[0]), 0)]
U = []

# Simulation
for i, t in enumerate(T[:-1]):
    efforts = controller(states[i])
    states.append(quadboi.step_dynamics(states[i], efforts, dt, wind(t)))
    P.append(states[i+1].pose.lin)
    Q.append(states[i+1].pose.ang)
    V.append(states[i+1].twist.lin)
    W.append(states[i+1].twist.ang)
    U.append([efforts[key] for key in quadboi.thruster_keys])

# Main figures
fig = pyplot.figure()
fig.suptitle("Results", fontsize=18)
A_ax = fig.add_subplot(2, 1, 1)
U_ax = fig.add_subplot(2, 1, 2)
P_fig = pyplot.figure()
P_ax = P_fig.add_subplot(111, projection="3d")

# Plot attitude Euler angles
A = np.rad2deg(map(motion.euler_from_quaternion, Q))
A_ax.plot(T, A[:, 0], 'r', label="roll")
A_ax.plot(T, A[:, 1], 'g', label="pitch")
A_ax.plot(T, A[:, 2], 'b', label="yaw")
A_ax.set_xlim([T[0], T[-1]])
A_ax.set_ylabel("Attitude Angle (deg)", fontsize=14)
A_ax.legend(fontsize=12)
A_ax.grid(True)

# Plot thruster efforts
U = np.vstack((np.array(U), [0, 0, 0, 0]))
U_ax.plot(T, U[:, 0], 'r', label=quadboi.thruster_keys[0])
U_ax.plot(T, U[:, 1], 'g', label=quadboi.thruster_keys[1])
U_ax.plot(T, U[:, 2], 'b', label=quadboi.thruster_keys[2])
U_ax.plot(T, U[:, 3], 'm', label=quadboi.thruster_keys[3])
U_ax.set_xlim([T[0], T[-1]])
U_ax.set_ylabel("Thruster Effort (RPM)", fontsize=14)
U_ax.legend(fontsize=12)
U_ax.grid(True)
U_ax.set_xlabel("Time (s)", fontsize=14)

# Plot position trajectory
P = np.array(P)
P_ax.set_title("World Position Trajectory", fontsize=18)
P_ax.plot(P[::2, 0], P[::2, 1], P[::2, 2], 'k')
P_ax.scatter(P[0, 0], P[0, 1], P[0, 2], c='k', s=30)
P_ax.scatter(P[-1, 0], P[-1, 1], P[-1, 2], c='g', s=30)
ground_xx, ground_yy = np.meshgrid(np.linspace(np.min(P[:, 0]-5), np.max(P[:, 0]+5), 5),
                                   np.linspace(np.min(P[:, 1]-5), np.max(P[:, 1]+5), 5))
P_ax.plot_surface(ground_xx, ground_yy, np.zeros_like(ground_xx), color='b', alpha=0.2)
P_ax.set_xlabel("x (m)", fontsize=14)
P_ax.set_ylabel("y (m)", fontsize=14)
P_ax.set_zlabel("z (m)", fontsize=14)
P_ax.grid(True)
P_ax.axis("equal")

pyplot.show()
